### ISSUE TITLE
purrr package conflict with map package (may only occur under windows64)

### ISSUE THREAD

**Issue by MariosRichards** [pkremp/polls#5]
Soluble by inserting this line runmodel.R in line 444 between:
detach("package:purrr", unload=TRUE) # because no longer needed and creates conflict with maps

443: 'save.image("out.RData")'

444: 'render("report.Rmd")'

**Comment by pkremp** [comment]
I haven't seen this one, but yes, that makes sense! I will add it.

**Comment by MariosRichards** [comment]
Dear Pkremp,
   Thankyou!
      Marios
